language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"
  - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - pip install simple-salesforce==0.67.0
  - git clone https://github.com/OCA/server-tools ${HOME}/server-tools -b ${VERSION}
  - git clone https://github.com/OCA/connector ${HOME}/connector -b ${VERSION}
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  coveralls
